<?xml version="1.0" encoding="utf-8"?><Database Name="EduSafe" Class="DataBaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-DENT5RFJ;Initial Catalog=EduSafe;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="EduSafe.Properties.Settings" SettingsPropertyName="EduSafeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nama" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="update_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Comment" Member="Comments">
    <Type Name="Comment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="thread_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="comment" Member="comment1" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="user_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="update_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="delete_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Thread_Comment" Member="Thread" ThisKey="thread_Id" OtherKey="id" Type="Thread" IsForeignKey="true" />
      <Association Name="User_Comment" Member="User" ThisKey="user_Id" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Thread" Member="Threads">
    <Type Name="Thread">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="judul" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="isi" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="deleted_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="update_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Thread_Comment" Member="Comments" ThisKey="id" OtherKey="thread_Id" Type="Comment" />
      <Association Name="User_Thread" Member="User" ThisKey="user_Id" OtherKey="id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nama" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="delete_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="update_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="kelas" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_Comment" Member="Comments" ThisKey="id" OtherKey="user_Id" Type="Comment" />
      <Association Name="User_Thread" Member="Threads" ThisKey="id" OtherKey="user_Id" Type="Thread" />
    </Type>
  </Table>
</Database>