namespace EduSafe
{
    partial class FormThread
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormThread));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.dgvDataComment = new System.Windows.Forms.DataGridView();
            this.tbSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dgvData = new System.Windows.Forms.DataGridView();
            this.label1 = new System.Windows.Forms.Label();
            this.tbNama = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbJudul = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbIsi = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnHapus = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tbKelas = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbStatus = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnAktif = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnExel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuGroupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDataComment)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvData)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox1.BorderRadius = 5;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.dgvDataComment);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuGroupBox1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(70)))));
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(42, 530);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(898, 205);
            this.bunifuGroupBox1.TabIndex = 37;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Comment";
            // 
            // dgvDataComment
            // 
            this.dgvDataComment.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDataComment.BackgroundColor = System.Drawing.Color.White;
            this.dgvDataComment.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.None;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle1.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle1.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvDataComment.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvDataComment.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.SystemColors.Window;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(70)))), ((int)(((byte)(70)))));
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvDataComment.DefaultCellStyle = dataGridViewCellStyle2;
            this.dgvDataComment.Location = new System.Drawing.Point(22, 37);
            this.dgvDataComment.Name = "dgvDataComment";
            this.dgvDataComment.RowHeadersWidth = 51;
            this.dgvDataComment.RowTemplate.Height = 24;
            this.dgvDataComment.Size = new System.Drawing.Size(855, 148);
            this.dgvDataComment.TabIndex = 24;
            // 
            // tbSearch
            // 
            this.tbSearch.AcceptsReturn = false;
            this.tbSearch.AcceptsTab = false;
            this.tbSearch.AnimationSpeed = 200;
            this.tbSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbSearch.AutoSizeHeight = true;
            this.tbSearch.BackColor = System.Drawing.Color.Transparent;
            this.tbSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbSearch.BackgroundImage")));
            this.tbSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbSearch.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbSearch.BorderRadius = 15;
            this.tbSearch.BorderThickness = 1;
            this.tbSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSearch.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbSearch.DefaultText = "";
            this.tbSearch.FillColor = System.Drawing.Color.White;
            this.tbSearch.HideSelection = true;
            this.tbSearch.IconLeft = ((System.Drawing.Image)(resources.GetObject("tbSearch.IconLeft")));
            this.tbSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSearch.IconPadding = 10;
            this.tbSearch.IconRight = null;
            this.tbSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbSearch.Lines = new string[0];
            this.tbSearch.Location = new System.Drawing.Point(42, 84);
            this.tbSearch.MaxLength = 32767;
            this.tbSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbSearch.Modified = false;
            this.tbSearch.Multiline = false;
            this.tbSearch.Name = "tbSearch";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbSearch.OnIdleState = stateProperties4;
            this.tbSearch.Padding = new System.Windows.Forms.Padding(3);
            this.tbSearch.PasswordChar = '\0';
            this.tbSearch.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbSearch.PlaceholderText = "Cari judul thread..";
            this.tbSearch.ReadOnly = false;
            this.tbSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbSearch.SelectedText = "";
            this.tbSearch.SelectionLength = 0;
            this.tbSearch.SelectionStart = 0;
            this.tbSearch.ShortcutsEnabled = true;
            this.tbSearch.Size = new System.Drawing.Size(327, 43);
            this.tbSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbSearch.TabIndex = 36;
            this.tbSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbSearch.TextMarginBottom = 0;
            this.tbSearch.TextMarginLeft = 15;
            this.tbSearch.TextMarginTop = 0;
            this.tbSearch.TextPlaceholder = "Cari judul thread..";
            this.tbSearch.UseSystemPasswordChar = false;
            this.tbSearch.WordWrap = true;
            this.tbSearch.TextChanged += new System.EventHandler(this.tbSearch_TextChanged);
            // 
            // dgvData
            // 
            this.dgvData.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvData.BackgroundColor = System.Drawing.Color.White;
            this.dgvData.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.None;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.SystemColors.Control;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle3.ForeColor = System.Drawing.SystemColors.WindowText;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvData.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle3;
            this.dgvData.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle4.BackColor = System.Drawing.SystemColors.Window;
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Poppins", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvData.DefaultCellStyle = dataGridViewCellStyle4;
            this.dgvData.Location = new System.Drawing.Point(42, 145);
            this.dgvData.Name = "dgvData";
            this.dgvData.RowHeadersWidth = 51;
            this.dgvData.RowTemplate.Height = 24;
            this.dgvData.Size = new System.Drawing.Size(898, 152);
            this.dgvData.TabIndex = 24;
            this.dgvData.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvData_CellClick);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Poppins", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(385, 22);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(207, 53);
            this.label1.TabIndex = 25;
            this.label1.Text = "Thread User";
            // 
            // tbNama
            // 
            this.tbNama.AcceptsReturn = false;
            this.tbNama.AcceptsTab = false;
            this.tbNama.AnimationSpeed = 200;
            this.tbNama.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbNama.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbNama.AutoSizeHeight = true;
            this.tbNama.BackColor = System.Drawing.Color.Transparent;
            this.tbNama.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbNama.BackgroundImage")));
            this.tbNama.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbNama.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbNama.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbNama.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbNama.BorderRadius = 15;
            this.tbNama.BorderThickness = 1;
            this.tbNama.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbNama.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNama.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbNama.DefaultText = "";
            this.tbNama.FillColor = System.Drawing.Color.White;
            this.tbNama.HideSelection = true;
            this.tbNama.IconLeft = null;
            this.tbNama.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNama.IconPadding = 10;
            this.tbNama.IconRight = null;
            this.tbNama.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbNama.Lines = new string[0];
            this.tbNama.Location = new System.Drawing.Point(42, 327);
            this.tbNama.MaxLength = 32767;
            this.tbNama.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbNama.Modified = false;
            this.tbNama.Multiline = false;
            this.tbNama.Name = "tbNama";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNama.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbNama.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNama.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbNama.OnIdleState = stateProperties8;
            this.tbNama.Padding = new System.Windows.Forms.Padding(3);
            this.tbNama.PasswordChar = '\0';
            this.tbNama.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbNama.PlaceholderText = "Nama";
            this.tbNama.ReadOnly = false;
            this.tbNama.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbNama.SelectedText = "";
            this.tbNama.SelectionLength = 0;
            this.tbNama.SelectionStart = 0;
            this.tbNama.ShortcutsEnabled = true;
            this.tbNama.Size = new System.Drawing.Size(209, 43);
            this.tbNama.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbNama.TabIndex = 26;
            this.tbNama.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbNama.TextMarginBottom = 0;
            this.tbNama.TextMarginLeft = 4;
            this.tbNama.TextMarginTop = -1;
            this.tbNama.TextPlaceholder = "Nama";
            this.tbNama.UseSystemPasswordChar = false;
            this.tbNama.WordWrap = true;
            // 
            // tbJudul
            // 
            this.tbJudul.AcceptsReturn = false;
            this.tbJudul.AcceptsTab = false;
            this.tbJudul.AnimationSpeed = 200;
            this.tbJudul.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbJudul.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbJudul.AutoSizeHeight = true;
            this.tbJudul.BackColor = System.Drawing.Color.Transparent;
            this.tbJudul.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbJudul.BackgroundImage")));
            this.tbJudul.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbJudul.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbJudul.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbJudul.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbJudul.BorderRadius = 15;
            this.tbJudul.BorderThickness = 1;
            this.tbJudul.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbJudul.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbJudul.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbJudul.DefaultText = "";
            this.tbJudul.FillColor = System.Drawing.Color.White;
            this.tbJudul.HideSelection = true;
            this.tbJudul.IconLeft = null;
            this.tbJudul.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbJudul.IconPadding = 10;
            this.tbJudul.IconRight = null;
            this.tbJudul.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbJudul.Lines = new string[0];
            this.tbJudul.Location = new System.Drawing.Point(42, 390);
            this.tbJudul.MaxLength = 32767;
            this.tbJudul.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbJudul.Modified = false;
            this.tbJudul.Multiline = false;
            this.tbJudul.Name = "tbJudul";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbJudul.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbJudul.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbJudul.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbJudul.OnIdleState = stateProperties12;
            this.tbJudul.Padding = new System.Windows.Forms.Padding(3);
            this.tbJudul.PasswordChar = '\0';
            this.tbJudul.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbJudul.PlaceholderText = "Judul";
            this.tbJudul.ReadOnly = false;
            this.tbJudul.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbJudul.SelectedText = "";
            this.tbJudul.SelectionLength = 0;
            this.tbJudul.SelectionStart = 0;
            this.tbJudul.ShortcutsEnabled = true;
            this.tbJudul.Size = new System.Drawing.Size(209, 43);
            this.tbJudul.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbJudul.TabIndex = 27;
            this.tbJudul.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbJudul.TextMarginBottom = 0;
            this.tbJudul.TextMarginLeft = 4;
            this.tbJudul.TextMarginTop = -1;
            this.tbJudul.TextPlaceholder = "Judul";
            this.tbJudul.UseSystemPasswordChar = false;
            this.tbJudul.WordWrap = true;
            // 
            // tbIsi
            // 
            this.tbIsi.AcceptsReturn = false;
            this.tbIsi.AcceptsTab = false;
            this.tbIsi.AnimationSpeed = 200;
            this.tbIsi.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbIsi.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbIsi.AutoSizeHeight = true;
            this.tbIsi.BackColor = System.Drawing.Color.Transparent;
            this.tbIsi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbIsi.BackgroundImage")));
            this.tbIsi.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbIsi.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbIsi.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbIsi.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbIsi.BorderRadius = 15;
            this.tbIsi.BorderThickness = 1;
            this.tbIsi.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbIsi.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbIsi.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbIsi.DefaultText = "";
            this.tbIsi.FillColor = System.Drawing.Color.White;
            this.tbIsi.HideSelection = true;
            this.tbIsi.IconLeft = null;
            this.tbIsi.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbIsi.IconPadding = 10;
            this.tbIsi.IconRight = null;
            this.tbIsi.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbIsi.Lines = new string[0];
            this.tbIsi.Location = new System.Drawing.Point(314, 327);
            this.tbIsi.MaxLength = 32767;
            this.tbIsi.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbIsi.Modified = false;
            this.tbIsi.Multiline = false;
            this.tbIsi.Name = "tbIsi";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbIsi.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbIsi.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbIsi.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbIsi.OnIdleState = stateProperties16;
            this.tbIsi.Padding = new System.Windows.Forms.Padding(3);
            this.tbIsi.PasswordChar = '\0';
            this.tbIsi.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbIsi.PlaceholderText = "Isi";
            this.tbIsi.ReadOnly = false;
            this.tbIsi.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbIsi.SelectedText = "";
            this.tbIsi.SelectionLength = 0;
            this.tbIsi.SelectionStart = 0;
            this.tbIsi.ShortcutsEnabled = true;
            this.tbIsi.Size = new System.Drawing.Size(209, 43);
            this.tbIsi.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbIsi.TabIndex = 29;
            this.tbIsi.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbIsi.TextMarginBottom = 0;
            this.tbIsi.TextMarginLeft = 4;
            this.tbIsi.TextMarginTop = -1;
            this.tbIsi.TextPlaceholder = "Isi";
            this.tbIsi.UseSystemPasswordChar = false;
            this.tbIsi.WordWrap = true;
            // 
            // btnHapus
            // 
            this.btnHapus.AllowAnimations = true;
            this.btnHapus.AllowMouseEffects = true;
            this.btnHapus.AllowToggling = false;
            this.btnHapus.AnimationSpeed = 200;
            this.btnHapus.AutoGenerateColors = false;
            this.btnHapus.AutoRoundBorders = false;
            this.btnHapus.AutoSizeLeftIcon = true;
            this.btnHapus.AutoSizeRightIcon = true;
            this.btnHapus.BackColor = System.Drawing.Color.Transparent;
            this.btnHapus.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnHapus.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHapus.BackgroundImage")));
            this.btnHapus.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHapus.ButtonText = "nonaktifkan";
            this.btnHapus.ButtonTextMarginLeft = 0;
            this.btnHapus.ColorContrastOnClick = 45;
            this.btnHapus.ColorContrastOnHover = 45;
            this.btnHapus.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnHapus.CustomizableEdges = borderEdges1;
            this.btnHapus.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHapus.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHapus.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnHapus.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnHapus.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHapus.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnHapus.ForeColor = System.Drawing.Color.White;
            this.btnHapus.IconLeft = null;
            this.btnHapus.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHapus.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnHapus.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnHapus.IconMarginLeft = 11;
            this.btnHapus.IconPadding = 10;
            this.btnHapus.IconRight = null;
            this.btnHapus.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHapus.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnHapus.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnHapus.IconSize = 25;
            this.btnHapus.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnHapus.IdleBorderRadius = 0;
            this.btnHapus.IdleBorderThickness = 0;
            this.btnHapus.IdleFillColor = System.Drawing.Color.Empty;
            this.btnHapus.IdleIconLeftImage = null;
            this.btnHapus.IdleIconRightImage = null;
            this.btnHapus.IndicateFocus = false;
            this.btnHapus.Location = new System.Drawing.Point(597, 327);
            this.btnHapus.Name = "btnHapus";
            this.btnHapus.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHapus.OnDisabledState.BorderRadius = 35;
            this.btnHapus.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHapus.OnDisabledState.BorderThickness = 1;
            this.btnHapus.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHapus.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHapus.OnDisabledState.IconLeftImage = null;
            this.btnHapus.OnDisabledState.IconRightImage = null;
            this.btnHapus.onHoverState.BorderColor = System.Drawing.Color.Crimson;
            this.btnHapus.onHoverState.BorderRadius = 35;
            this.btnHapus.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHapus.onHoverState.BorderThickness = 1;
            this.btnHapus.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnHapus.onHoverState.ForeColor = System.Drawing.Color.Crimson;
            this.btnHapus.onHoverState.IconLeftImage = null;
            this.btnHapus.onHoverState.IconRightImage = null;
            this.btnHapus.OnIdleState.BorderColor = System.Drawing.Color.Crimson;
            this.btnHapus.OnIdleState.BorderRadius = 35;
            this.btnHapus.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHapus.OnIdleState.BorderThickness = 1;
            this.btnHapus.OnIdleState.FillColor = System.Drawing.Color.Crimson;
            this.btnHapus.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnHapus.OnIdleState.IconLeftImage = null;
            this.btnHapus.OnIdleState.IconRightImage = null;
            this.btnHapus.OnPressedState.BorderColor = System.Drawing.Color.Crimson;
            this.btnHapus.OnPressedState.BorderRadius = 35;
            this.btnHapus.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHapus.OnPressedState.BorderThickness = 1;
            this.btnHapus.OnPressedState.FillColor = System.Drawing.Color.Crimson;
            this.btnHapus.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnHapus.OnPressedState.IconLeftImage = null;
            this.btnHapus.OnPressedState.IconRightImage = null;
            this.btnHapus.Size = new System.Drawing.Size(150, 42);
            this.btnHapus.TabIndex = 32;
            this.btnHapus.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnHapus.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnHapus.TextMarginLeft = 0;
            this.btnHapus.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnHapus.UseDefaultRadiusAndThickness = true;
            this.btnHapus.Click += new System.EventHandler(this.btnHapus_Click);
            // 
            // tbKelas
            // 
            this.tbKelas.AcceptsReturn = false;
            this.tbKelas.AcceptsTab = false;
            this.tbKelas.AnimationSpeed = 200;
            this.tbKelas.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbKelas.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbKelas.AutoSizeHeight = true;
            this.tbKelas.BackColor = System.Drawing.Color.Transparent;
            this.tbKelas.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbKelas.BackgroundImage")));
            this.tbKelas.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbKelas.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbKelas.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbKelas.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbKelas.BorderRadius = 15;
            this.tbKelas.BorderThickness = 1;
            this.tbKelas.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbKelas.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbKelas.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbKelas.DefaultText = "";
            this.tbKelas.FillColor = System.Drawing.Color.White;
            this.tbKelas.HideSelection = true;
            this.tbKelas.IconLeft = null;
            this.tbKelas.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbKelas.IconPadding = 10;
            this.tbKelas.IconRight = null;
            this.tbKelas.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbKelas.Lines = new string[0];
            this.tbKelas.Location = new System.Drawing.Point(314, 390);
            this.tbKelas.MaxLength = 32767;
            this.tbKelas.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbKelas.Modified = false;
            this.tbKelas.Multiline = false;
            this.tbKelas.Name = "tbKelas";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbKelas.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbKelas.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbKelas.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbKelas.OnIdleState = stateProperties20;
            this.tbKelas.Padding = new System.Windows.Forms.Padding(3);
            this.tbKelas.PasswordChar = '\0';
            this.tbKelas.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbKelas.PlaceholderText = "Kelas";
            this.tbKelas.ReadOnly = false;
            this.tbKelas.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbKelas.SelectedText = "";
            this.tbKelas.SelectionLength = 0;
            this.tbKelas.SelectionStart = 0;
            this.tbKelas.ShortcutsEnabled = true;
            this.tbKelas.Size = new System.Drawing.Size(209, 43);
            this.tbKelas.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbKelas.TabIndex = 28;
            this.tbKelas.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbKelas.TextMarginBottom = 0;
            this.tbKelas.TextMarginLeft = 4;
            this.tbKelas.TextMarginTop = -1;
            this.tbKelas.TextPlaceholder = "Kelas";
            this.tbKelas.UseSystemPasswordChar = false;
            this.tbKelas.WordWrap = true;
            // 
            // tbStatus
            // 
            this.tbStatus.AcceptsReturn = false;
            this.tbStatus.AcceptsTab = false;
            this.tbStatus.AnimationSpeed = 200;
            this.tbStatus.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbStatus.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbStatus.AutoSizeHeight = true;
            this.tbStatus.BackColor = System.Drawing.Color.Transparent;
            this.tbStatus.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbStatus.BackgroundImage")));
            this.tbStatus.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbStatus.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbStatus.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbStatus.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbStatus.BorderRadius = 15;
            this.tbStatus.BorderThickness = 1;
            this.tbStatus.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbStatus.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbStatus.DefaultFont = new System.Drawing.Font("Poppins", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbStatus.DefaultText = "";
            this.tbStatus.FillColor = System.Drawing.Color.White;
            this.tbStatus.HideSelection = true;
            this.tbStatus.IconLeft = null;
            this.tbStatus.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbStatus.IconPadding = 10;
            this.tbStatus.IconRight = null;
            this.tbStatus.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbStatus.Lines = new string[0];
            this.tbStatus.Location = new System.Drawing.Point(42, 452);
            this.tbStatus.MaxLength = 32767;
            this.tbStatus.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbStatus.Modified = false;
            this.tbStatus.Multiline = false;
            this.tbStatus.Name = "tbStatus";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbStatus.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbStatus.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbStatus.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbStatus.OnIdleState = stateProperties24;
            this.tbStatus.Padding = new System.Windows.Forms.Padding(3);
            this.tbStatus.PasswordChar = '\0';
            this.tbStatus.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbStatus.PlaceholderText = "Status";
            this.tbStatus.ReadOnly = false;
            this.tbStatus.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbStatus.SelectedText = "";
            this.tbStatus.SelectionLength = 0;
            this.tbStatus.SelectionStart = 0;
            this.tbStatus.ShortcutsEnabled = true;
            this.tbStatus.Size = new System.Drawing.Size(209, 43);
            this.tbStatus.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbStatus.TabIndex = 38;
            this.tbStatus.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbStatus.TextMarginBottom = 0;
            this.tbStatus.TextMarginLeft = 4;
            this.tbStatus.TextMarginTop = -1;
            this.tbStatus.TextPlaceholder = "Status";
            this.tbStatus.UseSystemPasswordChar = false;
            this.tbStatus.WordWrap = true;
            // 
            // btnAktif
            // 
            this.btnAktif.AllowAnimations = true;
            this.btnAktif.AllowMouseEffects = true;
            this.btnAktif.AllowToggling = false;
            this.btnAktif.AnimationSpeed = 200;
            this.btnAktif.AutoGenerateColors = false;
            this.btnAktif.AutoRoundBorders = false;
            this.btnAktif.AutoSizeLeftIcon = true;
            this.btnAktif.AutoSizeRightIcon = true;
            this.btnAktif.BackColor = System.Drawing.Color.Transparent;
            this.btnAktif.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnAktif.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAktif.BackgroundImage")));
            this.btnAktif.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAktif.ButtonText = "aktifkan";
            this.btnAktif.ButtonTextMarginLeft = 0;
            this.btnAktif.ColorContrastOnClick = 45;
            this.btnAktif.ColorContrastOnHover = 45;
            this.btnAktif.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnAktif.CustomizableEdges = borderEdges2;
            this.btnAktif.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAktif.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAktif.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnAktif.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnAktif.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAktif.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAktif.ForeColor = System.Drawing.Color.White;
            this.btnAktif.IconLeft = null;
            this.btnAktif.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAktif.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAktif.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAktif.IconMarginLeft = 11;
            this.btnAktif.IconPadding = 10;
            this.btnAktif.IconRight = null;
            this.btnAktif.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAktif.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAktif.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAktif.IconSize = 25;
            this.btnAktif.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnAktif.IdleBorderRadius = 0;
            this.btnAktif.IdleBorderThickness = 0;
            this.btnAktif.IdleFillColor = System.Drawing.Color.Empty;
            this.btnAktif.IdleIconLeftImage = null;
            this.btnAktif.IdleIconRightImage = null;
            this.btnAktif.IndicateFocus = false;
            this.btnAktif.Location = new System.Drawing.Point(597, 327);
            this.btnAktif.Name = "btnAktif";
            this.btnAktif.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAktif.OnDisabledState.BorderRadius = 35;
            this.btnAktif.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAktif.OnDisabledState.BorderThickness = 1;
            this.btnAktif.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAktif.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAktif.OnDisabledState.IconLeftImage = null;
            this.btnAktif.OnDisabledState.IconRightImage = null;
            this.btnAktif.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnAktif.onHoverState.BorderRadius = 35;
            this.btnAktif.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAktif.onHoverState.BorderThickness = 1;
            this.btnAktif.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnAktif.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnAktif.onHoverState.IconLeftImage = null;
            this.btnAktif.onHoverState.IconRightImage = null;
            this.btnAktif.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnAktif.OnIdleState.BorderRadius = 35;
            this.btnAktif.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAktif.OnIdleState.BorderThickness = 1;
            this.btnAktif.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnAktif.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAktif.OnIdleState.IconLeftImage = null;
            this.btnAktif.OnIdleState.IconRightImage = null;
            this.btnAktif.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnAktif.OnPressedState.BorderRadius = 35;
            this.btnAktif.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAktif.OnPressedState.BorderThickness = 1;
            this.btnAktif.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnAktif.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAktif.OnPressedState.IconLeftImage = null;
            this.btnAktif.OnPressedState.IconRightImage = null;
            this.btnAktif.Size = new System.Drawing.Size(150, 42);
            this.btnAktif.TabIndex = 39;
            this.btnAktif.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAktif.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAktif.TextMarginLeft = 0;
            this.btnAktif.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAktif.UseDefaultRadiusAndThickness = true;
            this.btnAktif.Click += new System.EventHandler(this.btnAktif_Click);
            // 
            // btnExel
            // 
            this.btnExel.AllowAnimations = true;
            this.btnExel.AllowMouseEffects = true;
            this.btnExel.AllowToggling = false;
            this.btnExel.AnimationSpeed = 200;
            this.btnExel.AutoGenerateColors = false;
            this.btnExel.AutoRoundBorders = false;
            this.btnExel.AutoSizeLeftIcon = true;
            this.btnExel.AutoSizeRightIcon = true;
            this.btnExel.BackColor = System.Drawing.Color.Transparent;
            this.btnExel.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnExel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnExel.BackgroundImage")));
            this.btnExel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExel.ButtonText = "Report Exel";
            this.btnExel.ButtonTextMarginLeft = 0;
            this.btnExel.ColorContrastOnClick = 45;
            this.btnExel.ColorContrastOnHover = 45;
            this.btnExel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnExel.CustomizableEdges = borderEdges3;
            this.btnExel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnExel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExel.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnExel.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnExel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnExel.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnExel.ForeColor = System.Drawing.Color.White;
            this.btnExel.IconLeft = null;
            this.btnExel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnExel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnExel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnExel.IconMarginLeft = 11;
            this.btnExel.IconPadding = 10;
            this.btnExel.IconRight = null;
            this.btnExel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnExel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnExel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnExel.IconSize = 25;
            this.btnExel.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnExel.IdleBorderRadius = 0;
            this.btnExel.IdleBorderThickness = 0;
            this.btnExel.IdleFillColor = System.Drawing.Color.Empty;
            this.btnExel.IdleIconLeftImage = null;
            this.btnExel.IdleIconRightImage = null;
            this.btnExel.IndicateFocus = false;
            this.btnExel.Location = new System.Drawing.Point(790, 85);
            this.btnExel.Name = "btnExel";
            this.btnExel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExel.OnDisabledState.BorderRadius = 10;
            this.btnExel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExel.OnDisabledState.BorderThickness = 1;
            this.btnExel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExel.OnDisabledState.IconLeftImage = null;
            this.btnExel.OnDisabledState.IconRightImage = null;
            this.btnExel.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnExel.onHoverState.BorderRadius = 10;
            this.btnExel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExel.onHoverState.BorderThickness = 1;
            this.btnExel.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnExel.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnExel.onHoverState.IconLeftImage = null;
            this.btnExel.onHoverState.IconRightImage = null;
            this.btnExel.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnExel.OnIdleState.BorderRadius = 10;
            this.btnExel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExel.OnIdleState.BorderThickness = 1;
            this.btnExel.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnExel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnExel.OnIdleState.IconLeftImage = null;
            this.btnExel.OnIdleState.IconRightImage = null;
            this.btnExel.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnExel.OnPressedState.BorderRadius = 10;
            this.btnExel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExel.OnPressedState.BorderThickness = 1;
            this.btnExel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(251)))), ((int)(((byte)(168)))), ((int)(((byte)(52)))));
            this.btnExel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnExel.OnPressedState.IconLeftImage = null;
            this.btnExel.OnPressedState.IconRightImage = null;
            this.btnExel.Size = new System.Drawing.Size(150, 42);
            this.btnExel.TabIndex = 40;
            this.btnExel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnExel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnExel.TextMarginLeft = 0;
            this.btnExel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnExel.UseDefaultRadiusAndThickness = true;
            this.btnExel.Click += new System.EventHandler(this.btnExel_Click);
            // 
            // FormThread
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(983, 757);
            this.Controls.Add(this.btnExel);
            this.Controls.Add(this.btnAktif);
            this.Controls.Add(this.tbStatus);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Controls.Add(this.tbSearch);
            this.Controls.Add(this.dgvData);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.tbNama);
            this.Controls.Add(this.tbJudul);
            this.Controls.Add(this.tbIsi);
            this.Controls.Add(this.btnHapus);
            this.Controls.Add(this.tbKelas);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormThread";
            this.Text = "FormThread";
            this.Load += new System.EventHandler(this.FormThread_Load);
            this.bunifuGroupBox1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvDataComment)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvData)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private System.Windows.Forms.DataGridView dgvDataComment;
        private Bunifu.UI.WinForms.BunifuTextBox tbSearch;
        private System.Windows.Forms.DataGridView dgvData;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox tbNama;
        private Bunifu.UI.WinForms.BunifuTextBox tbJudul;
        private Bunifu.UI.WinForms.BunifuTextBox tbIsi;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHapus;
        private Bunifu.UI.WinForms.BunifuTextBox tbKelas;
        private Bunifu.UI.WinForms.BunifuTextBox tbStatus;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAktif;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnExel;
    }
}